### ISSUE TITLE
Fixing "Undefined global" warnings

### ISSUE THREAD

**Issue by fredrikaverpil** [HiPhish/neotest-busted#3]
Hi (again 😄) 👋 and thanks for making this nice adapter!

I'm just wondering, what is your recommendation on getting these symbols to not cause linting issues, and making it possible to perform e.g. `gd` (goto def) on them?

<img width="1407" alt="Screenshot 2024-05-11 at 06 28 23" src="https://github.com/HiPhish/neotest-busted/assets/994357/dfb90649-79ae-4f3b-b6ef-f20475a1d2be">

I'm not 100% sure, but I was thinking I could perhaps somehow use [neodev](https://github.com/folke/neodev.nvim) to fix this, by adding a `.neodev.json` with the following contents to the repo root:

```json
{
  "neodev": {
    "library": {
      "enabled": true,
      "plugins": true
    }
  },
  "neoconf": {
    "plugins": {
      "lua_ls": {
        "enabled": true
      }
    }
  }
}
```

On my end this works for the most part really well, but there are still some warnings:

<img width="1276" alt="image" src="https://github.com/HiPhish/neotest-busted/assets/994357/3966a249-b4ae-4fac-8577-8ab409186fcf">

What do you think would be the best solution here?

And if you're curious, here's my neovim config: https://github.com/fredrikaverpil/dotfiles/tree/main/nvim-fredrik

**Comment by HiPhish** [comment]
I'm afraid I don't have a good solution. It is not highlighted for me because I have [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) installed, which places its own `describe` into the global namespace. Jumping to the definition takes me to that `describe` as well. The culprit is `lua/plenary/busted.lua`, which is a [an ad hoc, informally-specified, bug-ridden, slow implementation of half of busted](https://en.wikipedia.org/wiki/Greenspun%27s_tenth_rule).

For the record, I consider this a mistake, I hate it when a plugin pollutes my global namespace with its own symbols for no reason. But it does keep the language server quiet, so there's that. I mean, if TJ wants to make Telescope depend on his grab-bag of Lua code then fine, but I don't like that a *library* is inserting code into the `_G` variable.

If you don't have plenary.nvim installed you could try adding the [busted definitions](https://github.com/LuaCATS/busted) to your language server configuration. Adding `${3rd}/busted/library` to your [`workspace.library`](https://luals.github.io/wiki/settings/#workspacelibrary) should be enough.

EDIT: I hindsight I think I expressed myself wrong in the second paragraph. Plenary does not add its own implementation of the busted functions into `_G` unless you explicitly `require` the module. This part is fine. However, the Lua language server does not execute code, it statically analyzes the files, notices that `busted.lua` defines global variables, and so it assumes that I want these global variables in my codebase. In a world without LSP TJ did everything right, but we live in a world with LSP now.

**Comment by fredrikaverpil** [comment]
Ok, no worries - thanks for having a look at this 😄 👍

**Comment by HiPhish** [comment]
Did you try adding `${3rd}/busted/library` to your settings? I think it would be useful for people who come across this thread in the future to know if it works.

**Comment by fredrikaverpil** [comment]
No, I didn't try that - I had to move on and used neotest-plenary instead as I was constantly finding myself in a rabbit hole with busted, unfortunately.
